
name: CI/CD with Terraform

on:
  push:
    branches:
      - main
      - Complete-CI/CD-with-Terraform and AWS

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "ap-south-1"
  AWS_TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_SSH_KEY_PRIVATE: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  AWS_SSH_KEY_PUBLIC: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  SERVER_PUBLIC_IP: ${{ secrets.SERVER_PUBLIC_IP }}


jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    outputs:
      SERVER_PUBLIC_IP: ${{ steps.set-ip.outputs.instance_public_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

  
  # ðŸ” Verify secrets injection
      - name: Verify secrets injection (SAFE)
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:+SET}"
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:+SET}"
          echo "AWS_TF_STATE_BUCKET_NAME=${AWS_TF_STATE_BUCKET_NAME:+SET}"
          echo "AWS_SSH_KEY_PRIVATE=${AWS_SSH_KEY_PRIVATE:+SET}"
          echo "AWS_SSH_KEY_PUBLIC=${AWS_SSH_KEY_PUBLIC:+SET}"

      - name: Write private key to file
        run: |
              mkdir -p ./terraform/keys
              echo "$AWS_SSH_KEY_PRIVATE" > ./terraform/keys/deployer.pem
              chmod 600 ./terraform/keys/deployer.pem
        working-directory: ./terraform


      - name: terraform init
        id: init
        run: terraform init -backend-config="bucket=$AWS_TF_STATE_BUCKET_NAME" -backend-config="region=$AWS_REGION"
        working-directory: ./terraform

      - name: terraform Plan
        id: plan
        run: |-
          terraform plan \
          -var="region=$AWS_REGION" \
          -var="public_key=$AWS_SSH_KEY_PUBLIC" \
          -var="key_name=deployer-key" \
          -out=PLAN
        working-directory: ./terraform

      - name: terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./terraform

      - name: Set Terraform output
        id: set-ip
        run: echo "instance_public_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform

  deploy-appl:
    environment: production
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set IP env variable
        run: echo "SERVER_PUBLIC_IP=${{ needs.deploy-infra.outputs.SERVER_PUBLIC_IP }}" >> $GITHUB_ENV

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build push docker image and run container
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: nodeapp
          IMAGE_TAG: ${{ github.sha }} 
        working-directory: ./nodeapp      
        run: |-
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy docker image on AWS EC2
        env: 
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: nodeapp
          IMAGE_TAG: ${{ github.sha }}
          AWS_DEFAULT_REGION: "ap-south-1"
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_PUBLIC_IP }}   # use correct env variable
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
          envs: AWS_SSH_KEY_PRIVATE,REGISTRY,REPOSITORY,IMAGE_TAG,AWS_DEFAULT_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
          script: |
            sudo apt update
            sudo apt install docker.io -y
            sudo apt install awscli -y
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REGISTRY
            docker stop myappcontainer || true
            docker rm myappcontainer || true
            docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
            docker run -d --name myappcontainer -p 80:3000 $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
